repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=2048]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--all, --, --check]
      - id: clippy
        args: [--all, --all-features, --tests, --, -D, warnings]
  - repo: local
    hooks:
      - id: test
        name: test
        entry: cargo test
        language: rust
        pass_filenames: false
        verbose: true
